### PR TITLE
bug 1431259: update web service certs

### PR DESCRIPTION
**Pull request by escattone**
This PR updates the certificate ARN for the web service ELB. The new cert has `cdn.mdn.mozilla.net` added to its list of additional names.

Do we need to create a new cert (with `cdn.mdn.mozilla.net` added) for the EU central region for the standby cluster as well? If so, we'll have to request a new one and then I can add it to the `regions/frankfurt/prod.mm.sh` file.

### CODE REVIEW

**Comment by metadave** [comment]
(from IRC)
It looks like the Frankfurt cert is missing most of the names as well, so they'll need to be included as well. See https://github.com/mozmeao/infra/issues/795 for more info

**Comment by escattone** [comment]
Thanks @metadave! I'll go ahead and request a new certificate for the web service ELB for the Frankfurt cluster.

**Comment by escattone** [comment]
@metadave @jwhitlock FYI. A new cert for the web service ELB in Frankfurt has been requested. It matches the new Portland cert, including `cdn.mdn.mozilla.net`.

**Comment by jgmize** [comment]
arn:aws:acm:eu-central-1:236517346949:certificate/cf35a587-76f9-44be-8220-66899cf945fc has been issued.

**Comment by metadave** [comment]
Cert applied to Portland cluster:

```
kubectl -n mdn-prod annotate service web service.beta.kubernetes.io/aws-load-balancer-ssl-cert=arn:aws:acm:us-west-2:236517346949:certificate/8b99db59-3310-402b-9266-2398e5733055
```

**Comment by escattone** [comment]
@jwhitlock Me too. I didn't realize until yesterday that certs for CloudFront instances have to be in `us-east-1` (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cnames-and-https-requirements.html#https-requirements-aws-region) so we couldn't re-use the cert for the ELB in Portland.

I added another commit that updates the `web` service cert ARN for Frankfurt (it reflects what has already been applied to the ELB in Frankfurt).

**Pull request merged**
