### PR TITLE
add new env overrides per infra issue 477

### PR DESCRIPTION
**Pull request by escattone**
This PR adds some new environment variables per https://github.com/mozmeao/infra/issues/477. It depends on https://github.com/mozmeao/mdn-k8s-private/pull/14 and a Docker image for Kuma created after merging https://github.com/mozilla/kuma/pull/4426.

### CODE REVIEW

**Comment by metadave** [comment]
@escattone should the email addresses be secrets instead (so they don't get spammed?). If they're already public, that's fine too. Feel free to merge!

**Comment by jwhitlock** [comment]
@escattone and I talked about this, and neither of us have a strong opinion on email secrecy.  The ``@developer.mozilla.org`` emails are "fake" emails, and don't receive email.  This may effect delivery, and we may need to change that at some point.  The ``ADMINS`` email is real, and is already in the kuma source. 🤷‍♂️

If spam or other considerations are a concern in the future, then we will probably want the new values to be secret. So, if it is not much trouble, let's make the emails a secret setting now, but keep the known values and defaults.

**Comment by escattone** [comment]
Thanks @metadave and @jwhitlock! I'll update this PR based on https://github.com/mozmeao/mdn-k8s-private/pull/17.

**Comment by metadave** [comment]
🍰

**Pull request merged**
