### PR TITLE
reorganize env vars

### PR DESCRIPTION
**Pull request by escattone**
This is another iteration of the `Makefile` and the YAML files. The environment variables have been significantly reorganized.

The following commands (from the `Makefile`) seem to work:
```
make aws-create-mysql-vol
make aws-describe-mysql-vols
make k8s-ns
make k8s-shared
make k8s-delete-shared
make k8s-mysql
make k8s-delete-mysql
```

When I run `make k8s-web`, the service is created without error, but the deployment currently fails because it is unable to mount the `shared` PVC due to a connection timeout. I'm debugging that issue but I may need to pair on that with @metadave .

### CODE REVIEW

**Comment by metadave** [comment]
@escattone I have to look in the morning, but I was having problems mounting EFS due to a timeout, guessing it's a firewall/networking issue.

**Comment by escattone** [comment]
@metadave That makes sense to me as well. I commented-out the mount to check for problems further down the line, and it looks like the "web" pod is having problems connecting to the `memcached` instance as well (which may be a similar issue?). We can take a look at this together tomorrow.

FYI. I also manually loaded the sample database into the dev MySQL instance doing this:
```
cd ~/repos/infra/apps/mdn/mdn-aws/k8s
wget -N https://mdn-downloads.s3-us-west-2.amazonaws.com/mdn_sample_db.sql.gz
gunzip mdn_sample_db.sql.gz
kc exec -i mysql-3391802274-m1qg3 -- mysql --user=root --password=kuma --database=developer_mozilla_org < mdn_sample_db.sql
```

**Comment by metadave** [comment]
@escattone I'll take a look at EFS and memcached this morning, I'm positive it's a networking issue. I created a [card](https://github.com/mozmeao/infra/issues/378) to tracking automating these resources.

**Comment by metadave** [comment]
@escattone by the way, you can skip the intermediate `gunzip` step:

```
zcat /foo/somebackup.sql.gz | mysql -u 'username' -p db ...
```

Also, [here's](https://github.com/mozmeao/mdn-mysql) where the Kuma DB instance is built, and [here's](https://github.com/mozmeao/mdn-mysql/tree/master/mysql-demo-helper) an image that will load a mysql backup into a running MySQL container. [This script](https://github.com/mozmeao/mdn-mysql/blob/master/mysql-demo-helper/load-mdn-db.sh) waits until the database is alive (via the [`urlwait`](https://github.com/pmclanahan/urlwait) command) before attempting a restore.

**Comment by metadave** [comment]
@ryan I'm recreating memcached in a different subnet, I'll have a URL shortly.

**Comment by escattone** [comment]
@metadave and I discussed this verbally,so I'm going to merge this work-in-progress. The next PR will contain the work that we discussed and outlined in our meeting:
- reorganize according to https://github.com/mozmeao/infra/issues/374#issuecomment-319452658
- add `kumascript` deployment
- allow the service type to be configurable for the `api` (`ClusterIP`) and `web` (`LoadBalancer` or `NodePort`) services

**Pull request merged**
