### PR TITLE
remove k8s-based mysql && use new private env vars in stage

### PR DESCRIPTION
**Pull request by escattone**
This PR removes the old k8s-based mysql service, deployment, and setup env vars, as well as uses the new private env vars for staging (see https://github.com/mozmeao/mdn-k8s-private/pull/6).

### CODE REVIEW

**Comment by escattone** [comment]
I haven't tried these yet, but wanted to open for comment.

**Comment by metadave** [comment]
How will this work for dev instances?

**Comment by metadave** [comment]
regarding stage secrets: https://github.com/mozmeao/infra/issues/463

**Comment by escattone** [comment]
Thanks @metadave. I'm not going to keep the "private env vars" idea since we're going to one-time deploy a k8s secrets resource and use that instead, but I'll merge this to keep the mysql-related clean-up and we'll iterate from there.

**Pull request merged**
